spring:
  profiles:
    group:
      test: "test"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
#    ?? ??? ??? ????? connection pool size ??
    hikari:
      connection-timeout: 6000
      maximum-pool-size: 40
#      max-lifetime: 30000

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            DEBUG
        transaction:
          DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
